### PR TITLE
Update start-server.sh

### PR DESCRIPTION
**Pull request by DemuraAIdev**
Add config name for newer version

### CODE REVIEW

**Comment by ich777** [comment]
@DemuraAIdev thanks for the PR.

If I add it like that, isn't the config name itself missing? The documentation [here](https://mindustrygame.github.io/wiki/servers/#dedicated-server-commands) mentions that you have to use it like:

> `config [name] [value...]`: Configure server settings.

However `config` is listed at "Dedicated Server Commands" not at "Dedicated Server Configuration Options" so to speak it is a console command or am I wrong about that?

Wouldn't it be also be an option to add it in the variable `GAME_PARAMS`?

**Comment by ich777** [comment]
@DemuraAIdev what are your thoughts on that?

**Comment by AltairAIDev** [comment]
yeah when i add` GAME_PARAMS= config name Mindustry` its work
> If I add it like that, isn't the config name itself missing? The documentation [here](https://mindustrygame.github.io/wiki/servers/#dedicated-server-commands) mentions that you have to use it like:
> config [name] [value...]: Configure server settings.
> However config is listed at "Dedicated Server Commands" not at "Dedicated Server Configuration Options" so to speak it is a console command or am I wrong about that?

nope if only set name its give error command not found 'name'
image

if config name
image

i think documentation is not updated?

**Comment by ich777** [comment]
> yeah when i add` GAME_PARAMS= config name Mindustry` its work

I think it's supposed to work differently or am I wrong about that?
`... config <NAMEFROMCONFIG> name ...`

I could be very wrong about that since I haven't got around to try it yet.

**Comment by AltairAIDev** [comment]
`config name ExampleName`
you need try to launch it before publish to public 🙄

**Comment by ich777** [comment]
@DemuraAIdev I've modernized the container a bit, you can now add a port mapping to your Docker run command for port 8080 in the container for a web-console, please see the updated run example in the README.md

Thanks for the PR, your issue is also fixed!

**Pull request closed without merging**
